-- Create New Schema
DROP SCHEMA IF EXISTS MYDB.JIRA_ANALYTICS;
CREATE SCHEMA MYDB.JIRA_ANALYTICS;

-- Create sequence for dimension keys
CREATE OR REPLACE SEQUENCE USER_DIM_SEQ;

-- USER DIMENSION
CREATE OR REPLACE TABLE USER_DIM (
    USER_KEY NUMBER(38,0) NOT NULL AUTOINCREMENT,
    USER_ID TEXT,
    NAME TEXT,
    USERNAME TEXT,
    EMAIL TEXT,
    LOCALE TEXT,
    TIMEZONE TEXT,
    IS_ACTIVE VARCHAR
);
INSERT INTO USER_DIM (USER_KEY, USER_ID, NAME, USERNAME, EMAIL, LOCALE, TIMEZONE, IS_ACTIVE)
SELECT 
    USER_DIM_SEQ.NEXTVAL AS USER_KEY,
    U.ID AS USER_ID,
    U.NAME,
    U.USERNAME,
    U.EMAIL,
    U.LOCALE,
    U.TIME_ZONE,
    CASE WHEN U.IS_ACTIVE = 'TRUE' THEN 'Yes' ELSE 'No' END AS IS_ACTIVE
FROM 
    "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER U;

--ROW COUNT: 104

-- SELECT * FROM MYDB.JIRA_ANALYTICS.USER_DIM;
-- SELECT COUNT(DISTINCT USER_KEY) FROM MYDB.JIRA_ANALYTICS.USER_DIM;
    
-- SELECT * FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER;
-- SELECT COUNT(DISTINCT ID) FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER;




-- Create sequence for dimension keys
CREATE OR REPLACE SEQUENCE PROJ_SEQ;

-- Project Dimension
CREATE or REPLACE TABLE PROJECT_DIM (
    PROJECT_KEY NUMBER(38,0) NOT NULL autoincrement,
    PROJECT_ID NUMBER(38,0) NOT NULL,
    PROJECT_INTERNAL_KEY TEXT,
    PROJECT_NAME TEXT,
    PROJECT_LEAD TEXT,
    PROJECT_PERMISSION_SCHEME TEXT
);
INSERT INTO PROJECT_DIM (PROJECT_KEY,
    PROJECT_ID,
    PROJECT_INTERNAL_KEY,
    PROJECT_NAME,
    PROJECT_LEAD,
    PROJECT_PERMISSION_SCHEME)
SELECT
    PROJ_SEQ.NEXTVAL as PROJECT_KEY,
    P.ID AS PROJECT_ID,
    P.KEY AS PROJECT_INTERNAL_KEY,
    P.NAME AS PROJECT_NAME,
    U.NAME AS PROJECT_LEAD,
    PS.NAME AS PROJECT_PERMISSION_SCHEME
FROM 
    "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".PROJECT P 
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER U
ON P.LEAD_ID = U.ID 
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".PERMISSION_SCHEME PS
ON P.PERMISSION_SCHEME_ID = PS.ID;

--ROW COUNT 96

-- SELECT * FROM MYDB.JIRA_ANALYTICS.PROJECT_DIM ORDER BY PROJECT_ID;
-- SELECT COUNT(DISTINCT PROJECT_KEY) FROM MYDB.JIRA_ANALYTICS.PROJECT_DIM;
    
-- SELECT * FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".PROJECT ORDER BY ID;
-- SELECT COUNT(DISTINCT ID) FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".PROJECT;

CREATE OR REPLACE SEQUENCE LAST_SPR_SEQ;

--LAST SPRINT DIMENSION
CREATE or REPLACE TABLE LAST_SPRINT_DIM (
    LAST_SPRINT_KEY NUMBER(38,0) NOT NULL autoincrement,
    ISSUE_ID NUMBER,
    SPRINT_END_DATE DATE
);
INSERT INTO LAST_SPRINT_DIM (LAST_SPRINT_KEY,ISSUE_ID,
    SPRINT_END_DATE)
SELECT LAST_SPR_SEQ.NEXTVAL as LAST_SPRINT_KEY, ISSUE_ID,
SPRINT_END_DATE
FROM 
(SELECT I.ID AS ISSUE_ID,
MAX(DATE(S1.END_DATE)) AS SPRINT_END_DATE FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".ISSUE I
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".ISSUE_BOARD IB
ON I.ID = IB.ISSUE_ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".BOARD BR
ON IB.BOARD_ID = BR.ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".SPRINT_BOARD SP
ON BR.ID = SP.BOARD_ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".SPRINT S1
ON SP.SPRINT_ID = S1.ID
GROUP BY I.ID);

--ROW COUNT: 3924

-- SELECT * FROM LAST_SPRINT_DIM;



CREATE OR REPLACE SEQUENCE COM_SEQ;
-- COMMENT Dimension
CREATE or REPLACE TABLE COMMENT_DIM (
    COMMENT_KEY NUMBER(38,0) NOT NULL autoincrement,
    COMMENT_ID NUMBER,
    ISSUE_ID NUMBER,
    COMMENT_BODY TEXT,
    COMMENT_AUTHOR TEXT,
    COMMENT_IS_PUBLIC VARCHAR
);
INSERT INTO COMMENT_DIM (COMMENT_KEY,
    COMMENT_ID,
    ISSUE_ID,
    COMMENT_BODY,
    COMMENT_AUTHOR,
    COMMENT_IS_PUBLIC)
SELECT 
    COM_SEQ.NEXTVAL AS COMMENT_KEY,
    C.ID AS COMMENT_ID,
    C.ISSUE_ID AS ISSUE_ID,
    C.BODY AS COMMENT_BODY,
    U.NAME AS COMMENT_AUTHOR,
    CASE WHEN C.IS_PUBLIC = 'TRUE' THEN 'Yes' ELSE 'No' END AS COMMENT_IS_PUBLIC
FROM 
    "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".COMMENT C
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER U
ON C.AUTHOR_ID = U.ID;

--ROW COUNT : 8122

-- SELECT * FROM MYDB.JIRA_ANALYTICS.COMMENT_DIM ORDER BY COMMENT_ID;
-- SELECT COUNT(DISTINCT COMMENT_KEY) FROM MYDB.JIRA_ANALYTICS.COMMENT_DIM;
    
-- SELECT * FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".COMMENT ORDER BY ID;
-- SELECT COUNT(DISTINCT ID) FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".COMMENT;



-- ISSUE DIMENSION
CREATE OR REPLACE TABLE ISSUE_DIM (
    ISSUE_ID NUMBER NOT NULL,
    ISSUE_INTERNAL_KEY TEXT,
    ISSUE_TYPE TEXT,
    ISSUE_STATUS TEXT,
    ISSUE_ASSIGNEE TEXT,
    ISSUE_REPORTER TEXT,
    ISSUE_CREATOR TEXT,
    ISSUE_SUMMARY TEXT,
    ISSUE_DESCRIPTION TEXT,
    ISSUE_PRIORITY TEXT,
    ISSUE_RESOLUTION TEXT
);
INSERT INTO ISSUE_DIM (
    ISSUE_ID,
    ISSUE_INTERNAL_KEY,
    ISSUE_TYPE,
    ISSUE_STATUS,
    ISSUE_ASSIGNEE,
    ISSUE_REPORTER,
    ISSUE_CREATOR,
    ISSUE_SUMMARY,
    ISSUE_DESCRIPTION,
    ISSUE_PRIORITY,
    ISSUE_RESOLUTION
)
SELECT
    I.ID AS ISSUE_ID,
    I.KEY AS ISSUE_INTERNAL_KEY,
    IT.NAME AS ISSUE_TYPE,
    S.NAME AS ISSUE_STATUS,
    UA.NAME AS ISSUE_ASSIGNEE,
    UR.NAME AS ISSUE_REPORTER,
    UC.NAME AS ISSUE_CREATOR,
    I.SUMMARY AS ISSUE_SUMMARY,
    I.DESCRIPTION AS ISSUE_DESCRIPTION,
    P.NAME AS ISSUE_PRIORITY,
    R.NAME AS ISSUE_RESOLUTION

FROM
    "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".ISSUE I
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".ISSUE_TYPE IT
ON I.ISSUE_TYPE = IT.ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".STATUS S
ON I.STATUS = S.ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER UA
ON I.ASSIGNEE = UA.ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER UR
ON I.REPORTER = UR.ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".USER UC
ON I.CREATOR = UC.ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".PRIORITY P
ON I.PRIORITY = P.ID
LEFT JOIN "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".RESOLUTION R
ON I.RESOLUTION = R.ID;

--ROW COUNT: 3924


-- SELECT * FROM MYDB.JIRA_ANALYTICS.ISSUE_DIM ORDER BY ISSUE_ID;
-- SELECT COUNT(DISTINCT ISSUE_KEY) FROM MYDB.JIRA_ANALYTICS.ISSUE_DIM;
    
-- SELECT * FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".ISSUE WHERE DUE_DATE IS NOT NULL ORDER BY ID;
-- SELECT COUNT(DISTINCT ID) FROM "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".ISSUE;

-- ISSUE FACT  TABLE
CREATE OR REPLACE TABLE ISSUE_FACT (
    ISSUE_ID NUMBER(38,0) NOT NULL, 
    PROJECT_KEY NUMBER(38,0) NOT NULL, 
    CREATOR_USER_KEY NUMBER(38,0),
    ASSIGNEE_USER_KEY NUMBER(38,0),
    REPORTER_USER_KEY NUMBER(38,0), 
    LAST_SPRINT_KEY NUMBER(38,0), 
    ISSUE_CREATION_DATE_KEY NUMBER(38,0),
    ISSUE_UPDATED_DATE_KEY NUMBER(38,0),
    ISSUE_RESOLUTION_DATE_KEY NUMBER(38,0),
    ISSUE_CREATION_TIMEOFDAY_KEY NUMBER(38,0),
    ISSUE_UPDATED_TIMEOFDAY_KEY NUMBER(38,0),
    ISSUE_RESOLUTION_TIMEOFDAY_KEY NUMBER(38,0),
    ISSUE_DUEDATE_KEY NUMBER(38,0),
    ISSUE_TIMESPENT FLOAT
);


INSERT INTO ISSUE_FACT(
    ISSUE_ID, 
    PROJECT_KEY, 
    CREATOR_USER_KEY,
    ASSIGNEE_USER_KEY,
    REPORTER_USER_KEY,
    LAST_SPRINT_KEY, 
    ISSUE_CREATION_DATE_KEY,
    ISSUE_UPDATED_DATE_KEY,
    ISSUE_RESOLUTION_DATE_KEY,
    ISSUE_CREATION_TIMEOFDAY_KEY,
    ISSUE_UPDATED_TIMEOFDAY_KEY,
    ISSUE_RESOLUTION_TIMEOFDAY_KEY,
    ISSUE_DUEDATE_KEY,
    ISSUE_TIMESPENT
)
SELECT
    ID.ISSUE_ID,
    PD.PROJECT_KEY,
    UDC.USER_KEY AS CREATOR_USER_KEY,
    UDA.USER_KEY AS ASSIGNEE_USER_KEY,
    UDR.USER_KEY AS REPORTER_USER_KEY,
    LSD.LAST_SPRINT_KEY AS LAST_SPRINT_KEY,
    D_CREATED.DATE_KEY AS ISSUE_CREATION_DATE_KEY,
    D_UPDATED.DATE_KEY AS ISSUE_UPDATED_DATE_KEY,
    D_RESOLVED.DATE_KEY AS ISSUE_RESOLUTION_DATE_KEY,
    TOD_CREATED.TIMEOFDAY_KEY AS ISSUE_CREATION_TIMEOFDAY_KEY,
    TOD_UPDATED.TIMEOFDAY_KEY AS ISSUE_UPDATED_TIMEOFDAY_KEY,
    TOD_RESOLVED.TIMEOFDAY_KEY AS ISSUE_RESOLUTION_TIMEOFDAY_KEY,
    D_DUE.DATE_KEY AS ISSUE_DUEDATE_KEY,
    I.TIME_SPENT
FROM 
    "FWLOYYD_PZA82601_DATASLEEK_DW_UCLA2024"."DWH_UCLA2024_JIRA".ISSUE I

    LEFT JOIN "MYDB"."JIRA_ANALYTICS".ISSUE_DIM ID
    ON I.ID = ID.ISSUE_ID
    LEFT JOIN "MYDB"."JIRA_ANALYTICS".PROJECT_DIM PD
    ON I.PROJECT = PD.PROJECT_ID
    LEFT JOIN "MYDB"."JIRA_ANALYTICS".USER_DIM UDC
    ON I.CREATOR = UDC.USER_ID
    LEFT JOIN "MYDB"."JIRA_ANALYTICS".USER_DIM UDA
    ON I.ASSIGNEE = UDA.USER_ID
    LEFT JOIN "MYDB"."JIRA_ANALYTICS".USER_DIM UDR
    ON I.REPORTER = UDR.USER_ID
    LEFT JOIN "MYDB"."JIRA_ANALYTICS".LAST_SPRINT_DIM LSD 
    ON I.ID = LSD.ISSUE_ID
    

    LEFT JOIN "MYDB"."JIRA_ANALYTICS"."DATE_DIM" D_CREATED ON TO_NUMBER(TO_VARCHAR(TO_DATE(I.CREATED),'YYYYMMDD')) = D_CREATED.DATE_KEY
    LEFT JOIN "MYDB"."JIRA_ANALYTICS"."DATE_DIM" D_UPDATED ON TO_NUMBER(TO_VARCHAR(TO_DATE(I.UPDATED),'YYYYMMDD')) = D_UPDATED.DATE_KEY
    LEFT JOIN "MYDB"."JIRA_ANALYTICS"."DATE_DIM" D_RESOLVED ON TO_NUMBER(TO_VARCHAR(TO_DATE(I.RESOLVED),'YYYYMMDD')) = D_RESOLVED.DATE_KEY

    LEFT JOIN "MYDB"."JIRA_ANALYTICS"."DATE_DIM" D_DUE ON TO_NUMBER(TO_VARCHAR(TO_DATE(LSD.SPRINT_END_DATE),'YYYYMMDD')) = D_DUE.DATE_KEY
    
    LEFT JOIN "MYDB"."JIRA_ANALYTICS"."TIMEOFDAY_DIM" TOD_CREATED  ON HOUR(I.CREATED) = TOD_CREATED.HOUR_24
    LEFT JOIN "MYDB"."JIRA_ANALYTICS"."TIMEOFDAY_DIM" TOD_UPDATED  ON HOUR(I.UPDATED) = TOD_UPDATED.HOUR_24
    LEFT JOIN "MYDB"."JIRA_ANALYTICS"."TIMEOFDAY_DIM" TOD_RESOLVED  ON HOUR(I.RESOLVED) = TOD_RESOLVED.HOUR_24;

--ROW COUNT: 3924

    -- SELECT * FROM "MYDB"."JIRA_ANALYTICS".ISSUE_FACT ORDER BY ISSUE_ID LIMIT 200;

    -- SELECT COUNT( ISSUE_ID) , ISSUE_ID FROM "MYDB"."JIRA_ANALYTICS".ISSUE_FACT GROUP BY ISSUE_ID ORDER BY COUNT(ISSUE_ID) DESC;